### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by stefano-b**

### CODE REVIEW

**Comment by fabiospampinato** [comment]
I'm not sure Trimage is actually available on macOS and Windows, where can I download it for macOS for instance? And SVG Cleaner is too specific for our use case, you're going to want to use a general purpose image compressor with this extension.

Maybe just add Trimage to the Linux section?

**Comment by stefano-b** [comment]
I'm sorry, it was an oversight on my part, on the site it is advertised as cross-platform, and honestly I have not double-checked the availability. Sorry.

And I understand your reasoning about SVG Cleaner.

I'll just add Trimage to the Linux section as you suggest.

Thank you for your patience :)

**Comment by fabiospampinato** [comment]
No problem. Can you also remove the `*(Mac/Windows/Linux)*` part?

**Comment by stefano-b** [comment]
Done!

**Comment by fabiospampinato** [comment]
Thanks!

**Pull request merged**
